export const projects = [
  {
    name: "Ninja School",
    image: "NinjaSchool.jpg",
    live_demo: "https://ninja-school-33068.web.app",
    source_code: "https://github.com/faysalewucse/Ninja-School-Frontend",
    type: "web",
    features: [
      "Admin Dashboard",
      "Student Dashboard",
      "Instructor Dashboard",
      "Light/Dark Mode",
      "Stripe Js Implemention for payment",
      "MongoDB Aggregations.",
      "Google Sign In.",
      "AOS Package and Framer Motion Framework used for animation.",
      "NextUI react component",
      "Dynamic Title",
      "ChartJs Implementation],",
    ],
  },
  {
    name: "Online Quiz Taker",
    image: "QuizApp.png",
    live_demo: "https://quiztaker.netlify.app/",
    source_code: "https://github.com/faysalewucse/Quiz-App-React-RTK-Firebase",
    type: "web",
    features: [
      "User Authentication",
      "Quiz Creation",
      "Quiz Perticipation",
      "Quiz Question Updation",
    ],
  },
  {
    name: "Toy Galaxy",
    image: "ToyGalaxy.jpg",
    live_demo: "https://toygalaxy-b2ef0.web.app/",
    source_code: "https://github.com/faysalewucse/Toy-Galaxy-Frontend",
    type: "web",
    features: [
      "NextUI react component",
      "Dynamic Title",
      "AOS Package for Gallery Animation",
      "React Tab For Shop By Category",
      "Toy details.",
      "Search Toy",
      "Blog post.",
      "Redirect after login to the right page",
      "Forgot Password.",
      "Google Sign In.",
      "Gallery Image Download",
    ],
  },
  {
    name: "Baburchi Vai",
    image: "BaburchiVai.jpg",
    live_demo: "https://baburchivai.web.app/",
    source_code: "https://github.com/faysalewucse/Baburchi-Vai-Frontend-",
    type: "web",
    features: [
      "Chef list",
      "Chef recipes details",
      "Add Favourite recipe to the list",
      "Remove Favourite recip",
      "History of Favourite recipes",
      "Blog post",
      "User Profile Edit",
      "Forgot Password",
      "Google Sign In",
      "GitHub Sign In.",
    ],
  },
  {
    name: "Jobs Land",
    image: "JobsLand.jpg",
    live_demo: "https://jobsland.netlify.app/",
    source_code: "https://github.com/faysalewucse/Jobs-Land",
    type: "web",
    features: [
      "Jobs list",
      "Every Job Details",
      "Can Apply to the Jo",
      "Can't Apply to the job which a user already has been applied. alert for that",
      "History of applied jobs",
      "Filter from applied jobs",
      "Blog post",
    ],
  },
  {
    name: "Quran Learning System",
    image: "LLQ.jpg",
    live_demo: "https://letslearnquran.netlify.app",
    source_code: "https://github.com/faysalewucse/Lets-Learn-Quran",
    type: "web",
    features: [
      "Last Read BookMarks",
      "API Integration",
      "All Surah List with Audio",
    ],
  },

  {
    name: "6 Redux Projects",
    image: "redux.png",
    live_demo:
      "https://learnwithsumit.com/certificates/verify/LWSCTXN-8JXIW67G",
    source_code: "",
    type: "web",
  },
  {
    name: "An Islamic App",
    image: "Muhasaba.jpg",
    live_demo: "",
    source_code: "",
    type: "mobile",
  },
];
